---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myblog
  name: myblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myvblog
  template:
    metadata:
      labels:
        app: myblog
    spec:
      containers:
      - image: quay.io/rasulkarimov/myblog:latest
        imagePullPolicy: Always
        name: myblog

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myblog
  name: myblog
spec:
  ports:
  - nodePort: 32222
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myblog
  type: NodePort
